# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb54fb59e3fb5accd1d38189b67f1d2534b2abab5ff93635ac4e5d0bbe2803b30b03d592f6355c588a10d5f55d0a7b40a27b14b8a323ffcb7eeba3ede4e640e8

test:
  secret_key_base: b4543ea26013359016781b5cfe51a0ae09968e5f7f66b3d83310c3ea8487eb474b221be09c64d32cac7a77cd48ae937a928115e4c254d6eb9b8b543e894de379

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
